# Generated by Django 4.0.3 on 2022-03-24 12:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Banner')),
                ('Link', models.SlugField(max_length=250)),
                ('Height', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('Position_x', models.IntegerField()),
                ('Position_y', models.IntegerField()),
                ('Border_radius', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
